#!/usr/bin/env bash
# Vérifier si une adresse IP est fournie en tant qu'argument
if [ -z "$1" ]; then
  echo "Utilisation : $0 {ADRESSE_IP}"
  exit 1
fi

adresseIP=$"1"

pintResult=$(ping -c 5 "$adresseIP")

echo "$pintResult"
