#!/usr/bin/env bash

# Vérifier si une adresse IP est fournie en tant qu'argument
if [ -z "$1" ]; then
  echo "Utilisation : $0 {ADRESSE_IP}"
  exit 1
fi

# Initialise la variable pour extraire l'adresse IP de l'argument.
adresseIP=$"1"

# Effectuer un ping vers l'adresse IP (5 fois)
pintResult=$(ping -c 5 "$adresseIP")

# Afficher les résultats du ping
echo "$pintResult"
